
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ci
      POSTGRES_PASSWORD: ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: docker compose build
      - run: docker compose up -d

      - run: pip install -r requirements.txt
      - run: pytest tests --junit-xml=test-results.xml
        env:
          APP_URL: http://localhost:8002

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results

      - run: docker compose logs app
        if: failure()

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: gh release create $(git rev-parse --short HEAD) --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish on docker hub
        run: echo "Publishing..."

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on production
        run: echo "Deploying..."
